### PR TITLE
Implement support for bidirectional relationships.

### LINKED ISSUE #8: Support for Bidirectional Relationships
Say you have an Album entity:
```sql
CREATE TABLE album (
    album_id INTEGER PRIMARY KEY AUTOINCREMENT,
    producer_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    ...
    FOREIGN KEY(producer_id) REFERENCES person(person_id) DEFERRABLE INITIALLY DEFERRED
)
```

And a person entity:
```sql
CREATE TABLE person (
    person_id INTEGER PRIMARY KEY AUTOINCREMENT,
    favorite_album_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    ...
    FOREIGN KEY(favorite_album_id) REFERENCES Album(album_id) DEFERRABLE INITIALLY DEFERRED
)
```

Assume Rick Rubin produced the album La Futura by ZZ Top, and it is also his favorite album.  The DBIx code to create these entities would be:
```perl
my $la_futura = $schema->resultset('Album')->create({
    name => 'La Futura',
});
my $rick_rubin = $la_futura->create_related('producer', {
    name => 'Rick Rubin',
});
$rick_rubin->favorite_album($la_futura);
```

This type of bi-directional relationship does not appear to be supported by DBIx::Class::EasyFixture.

My suggestion to resolve this issue is by handling a `deferred` key in the `requires` hash:
```perl
my %definition_for = (
    'la_futura' => {
        new => 'Album',
        requires => {
            'rick_rubin' => {
                our => 'producer_id',
                their => 'person_id',
            },
        },
        using => {
            name => 'La Futura',
        },
    },

    'rick_rubin' => {
        new => 'Person',
        requires => {
            'la_futura' => {
                our => 'favorite_album_id',
                their => 'album_id',
                deferred => 1,
            },
        },
        using => {
            name => 'Rick Rubin',
        },
    },
);
```

If a required entity is flagged as `deferred`, this causes the handling of the required entity to be deferred, as if it were included in the `next` array, while the current entity is created first, as if the given required entity were not present in the `requires` hash.  Once both entities have been created, the relationship between the two is filled in.

If you think this is a good approach to resolving this issue, would you like me to work on a pull request?

### PR DESCRIPTION
**Pull request by lohengrin332**
@Ovid,

I'm sorry this took so long, but $work kicked into high gear soon after we discussed a solution to this problem.

Please let me know if you have any concerns about this pull request which would prevent you from accepting it.  Thank you for your time, and for the work that you do.

Resolves #8

### CODE REVIEW

**Comment by Ovid** [comment]
J. David Lewis: thank you for this. I appreciate it :)

**Comment by lohengrin332** [comment]
@Ovid,

I'd like to incorporate this change into my development environment, so a new version would be helpful.  If you would like me to help with building or deploying this new version I'm happy to do so.  Thank you.

**Comment by Ovid** [comment]
It's uploaded. Sorry for the delay!

**Comment by lohengrin332** [comment]
Thank you, sir!

**Pull request merged**
